name: Windows Acceptance Tests

on:
  workflow_call

defaults:
  run:
    shell: cmd

jobs:
  windows_acceptance_tests:
    # windows image reference: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on: windows-latest
    steps:
      - name: switch to msys2 bash
        shell: bash
        run:
          echo "C:\\msys64\\usr\\bin" >> $GITHUB_PATH
      - name: download cfengine with cf-remote
        shell: bash
        run: |
          pacman -S --noconfirm python-pip
          pip install cf-remote
          cf-remote --version 3.18.x download x86_64 msi
          mv $HOME/.cfengine/cf-remote/packages/*.msi cfengine.msi
      - name: install cfengine
        shell: pwsh
        run: |
          Start-Process msiexec.exe -Wait -ArgumentList '/quiet /qn /i cfengine.msi /L*V c:\tmp.log'
          Get-Content c:\tmp.log
      - name: Checkout Core
        uses: actions/checkout@v4

      - name: setup tests
        shell: bash
        run: |
          cp -a "/c/Program Files/Cfengine" /d/a/
          cd /d/a/core/core/tests/acceptance && rm -rf 00_basics 01_vars 02_classes 10_files 14_reports 15_control 16_cf-serverd 21_methods 22_cf-runagent 26_cf-net 27_cf-secret 28_inform_testing
          cd /d/a/core/core/tests/acceptance && ./testall --bindir="/d/a/Cfengine/bin" --extraclasses=EXTRA ./05_processes/01_matching/process_count_found.cf
          cat /d/a/core/core/tests/acceptance/test.log || true

#      - name: find visual studio tools
#        run: |
#          dir "C:\Program Files"
#          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
#          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC"
# where is vcvarsall.bat? https://developercommunity.visualstudio.com/t/vcvarsallbat-fails-after-upgrade-from-2022-preview/1477538
      - name: hello world C program
        shell: cmd
        run: |
          echo "start of cmd.exe commands..."
          cd
          dir
          REM type "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
          REM set VSCMD_DEBUG=3
          REM set
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          REM set
          echo "calling cl hello.c"
          cl hello.c
          echo "after cl hello.c"
          dir
          hello.exe
          echo "end of cmd.exe commands"
