name: Windows Acceptance Tests

on:
  workflow_call

jobs:
  windows_acceptance_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout Core
        uses: actions/checkout@v3

      - name: hello world C program
        run: |
          cl hello.c
          hello
