name: Windows Acceptance Tests

on:
  workflow_call

defaults:
  run:
    shell: cmd
jobs:
  windows_acceptance_tests:
    # windows image reference: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on: windows-latest
    steps:
      - name: Checkout Core
        uses: actions/checkout@v4

#      - name: find visual studio tools
#        run: |
#          dir "C:\Program Files"
#          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
#          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC"
# where is vcvarsall.bat? https://developercommunity.visualstudio.com/t/vcvarsallbat-fails-after-upgrade-from-2022-preview/1477538
      - name: hello world C program
        run: |
          echo "start of cmd.exe commands..."
          cd
          dir
          REM type "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
          REM set VSCMD_DEBUG=3
          REM set
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          REM set
          echo "calling cl hello.c"
          cl hello.c
          echo "after cl hello.c"
          dir
          hello.exe
          echo "end of cmd.exe commands"
